use_frameworks!

target 'QXWTestObject_Example' do
  pod 'QXWTestObject', :path => '../'

  target 'QXWTestObject_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
